import { CoffeeRecipe, CustomerCharacter, CafeUpgrade } from './types';

export const COFFEE_RECIPES: CoffeeRecipe[] = [
  {
    id: 'spanish-latte',
    name: 'Spanish Latte',
    bicolTag: '✦ Best Seller',
    temperature: 'hot',
    price: 148,
    ingredients: {
      coffee: 'espresso',
      milk: 'condensed_milk',
      topping: 'none',
      ice: false,
    },
    description: 'Double espresso with sweet condensed milk and silky foam',
    icon: '☕',
    cupColor: '#D4A373',
  },
  {
    id: 'biscoff-latte-iced',
    name: 'Iced Biscoff Latte',
    bicolTag: '✦ Best Seller • ✹ Premium',
    temperature: 'iced',
    price: 198,
    ingredients: {
      coffee: 'espresso',
      milk: 'steamed_milk',
      topping: 'biscoff',
      ice: true,
    },
    description: 'Rich espresso, cold milk, Lotus Biscoff crumb and ice',
    icon: '🍪',
    cupColor: '#C68B59',
  },
  {
    id: 'coconut-latte',
    name: 'Bicol Coconut Latte',
    bicolTag: '✹ Uniquely Ours',
    temperature: 'hot',
    price: 148,
    ingredients: {
      coffee: 'espresso',
      milk: 'coconut_milk',
      topping: 'coconut_flakes',
      ice: false,
    },
    description: 'Espresso infused with fresh Albay coconut milk',
    icon: '🥥',
    cupColor: '#E29578',
  },
  {
    id: 'iced-caramel-macchiato',
    name: 'Iced Caramel Macchiato',
    bicolTag: 'Popular Courtyard Brew',
    temperature: 'iced',
    price: 178,
    ingredients: {
      coffee: 'espresso',
      milk: 'steamed_milk',
      topping: 'caramel',
      ice: true,
    },
    description: 'Layered vanilla milk, espresso shot, and golden caramel swirl',
    icon: '🍯',
    cupColor: '#B08968',
  },
  {
    id: 'strawberry-choco',
    name: 'Iced Strawberry Choco',
    bicolTag: 'Sweet Fruit & Cocoa',
    temperature: 'iced',
    price: 178,
    ingredients: {
      coffee: 'chocolate',
      milk: 'chocolate_milk',
      topping: 'caramel',
      ice: true,
    },
    description: 'Decadent chocolate milk with sweet strawberry drizzle and ice',
    icon: '🍓',
    cupColor: '#6B4226',
  },
  {
    id: 'nutella-milktea',
    name: 'Nutella Milk Tea with Pearl',
    bicolTag: '✦ Best Seller Tea',
    temperature: 'iced',
    price: 138,
    ingredients: {
      coffee: 'tea',
      milk: 'steamed_milk',
      topping: 'boba',
      ice: true,
    },
    description: 'Ceylon black tea, creamy milk, Nutella blend, and chewy boba',
    icon: '🧋',
    cupColor: '#7F5539',
  },
];

export const CUSTOMER_ROSTERS: Omit<CustomerCharacter, 'id' | 'remainingPatience' | 'desiredRecipe'>[] = [
  {
    name: 'Maria Santos',
    role: 'Camalig Trail Hiker',
    avatar: '👩‍🌾',
    quote: 'Maayong aldaw! Need a sweet Spanish Latte before hiking the Camalig hills!',
    happyQuote: 'Salamat po! So warm and comforting, perfect sunrise brew!',
    maxPatience: 35,
  },
  {
    name: 'Kuya Mark',
    role: 'Albay Cyclist',
    avatar: '🚴‍♂️',
    quote: 'Just finished a ride from Legazpi! A cold Biscoff Latte please!',
    happyQuote: 'Lupet! The Biscoff crunch is so refreshing, salamat!',
    maxPatience: 32,
  },
  {
    name: 'Lola Carmen',
    role: 'Courtyard Regular',
    avatar: '👵',
    quote: 'A gentle Coconut Latte for an old lady please, using sweet gata.',
    happyQuote: 'Ay kay sarap! Tastes just like our home in Albay.',
    maxPatience: 40,
  },
  {
    name: 'Sofia Reyes',
    role: 'Architecture Student',
    avatar: '👩‍🎓',
    quote: 'Studying under the courtyard archway! An iced Caramel Macchiato to keep me awake.',
    happyQuote: 'Beautiful crema layers! Now I can finish my blueprints.',
    maxPatience: 30,
  },
  {
    name: 'Danilo',
    role: 'Mayon Artist',
    avatar: '🎨',
    quote: 'Painting Mount Mayon today! Can I get an iced Strawberry Choco?',
    happyQuote: 'Masterpiece in a cup! The inspiration I needed.',
    maxPatience: 34,
  },
];

export const INITIAL_UPGRADES: CafeUpgrade[] = [
  {
    id: 'golden_tamper',
    name: 'Golden Sun Tamper',
    cost: 300,
    icon: '✨',
    desc: 'Extracts richer espresso and grants +₱15 bonus tip per coffee.',
    unlocked: false,
  },
  {
    id: 'coconut_frother',
    name: 'Artisan Coconut Frother',
    cost: 500,
    icon: '🥥',
    desc: 'Extra-velvety microfoam adds +5 seconds customer patience.',
    unlocked: false,
  },
  {
    id: 'courtyard_monstera',
    name: 'Courtyard Garden Plants',
    cost: 800,
    icon: '🪴',
    desc: 'Brings cozy relaxing vibes, increasing customer joy rewards.',
    unlocked: false,
  },
];
